on:
  push:
    branches: "*"
  schedule:
    - cron: "0 0 * * *"
jobs:
  quiche:
    runs-on: ubuntu-20.04
    steps:
      - run: date +%Y-%m-%d
        id: date
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: quiche
          push: true
          tags:
            - ghcr.io/unasuke/curl-http3:quiche-${{ steps.date.outputs.result }}
            - ghcr.io/unasuke/curl-http3:quiche-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  ngtcp2:
    runs-on: ubuntu-20.04
    steps:
      - run: date +%Y-%m-%d
        id: date
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ngtcp2
          push: true
          tags:
            - ghcr.io/unasuke/curl-http3:ngtcp2-${{ steps.date.outputs.result }}
            - ghcr.io/unasuke/curl-http3:ngtcp2-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: build and test
        run: |
          ./build
          ./test

